--------------------------------------------------------
--  DDL for Table BASKET
--------------------------------------------------------

  CREATE TABLE "HKL"."BASKET" 
   (	"BASKET_MEMBER_ID" CHAR(15 BYTE), 
	"BASKET_PRODUCT_CODE" CHAR(6 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARD_ASK
--------------------------------------------------------

  CREATE TABLE "HKL"."BOARD_ASK" 
   (	"BOARD_ASK_NUMBER" NUMBER, 
	"BOARD_ASK_MEMBER_ID" CHAR(15 BYTE), 
	"BOARD_ASK_DATE" DATE, 
	"BOARD_ASK_CONTENT" VARCHAR2(3000 BYTE), 
	"BOARD_ASK_TITLE" VARCHAR2(200 BYTE), 
	"BOARD_ASK_STATE" CHAR(10 BYTE) DEFAULT '접수', 
	"BOARD_ASK_KIND" CHAR(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARD_COMMENT
--------------------------------------------------------

  CREATE TABLE "HKL"."BOARD_COMMENT" 
   (	"BOARD_COMMENT_BOARD_REVIEW_NUMBER" NUMBER, 
	"BOARD_COMMENT_NUMBER" VARCHAR2(20 BYTE), 
	"BOARD_COMMENT_CONTENT" VARCHAR2(3000 BYTE), 
	"BOARD_COMMENT_MEMBER_ID" CHAR(15 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARD_REVIEW
--------------------------------------------------------

  CREATE TABLE "HKL"."BOARD_REVIEW" 
   (	"BOARD_REVIEW_NUMBER" NUMBER, 
	"BOARD_REVIEW_MEMBER_ID" CHAR(15 BYTE), 
	"BOARD_REVIEW_PRODUCT_CODE" CHAR(6 BYTE), 
	"BOARD_REVIEW_TITLE" VARCHAR2(100 BYTE), 
	"BOARD_REVIEW_CONTENT" VARCHAR2(3000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "HKL"."MEMBER" 
   (	"MEMBER_ID" CHAR(15 BYTE), 
	"MEMBER_PW" VARCHAR2(30 BYTE), 
	"MEMBER_NAME" VARCHAR2(10 BYTE), 
	"MEMBER_EMAIL" VARCHAR2(40 BYTE), 
	"MEMBER_TEL" CHAR(12 BYTE), 
	"MEMBER_ADDRESS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "HKL"."PRODUCT" 
   (	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"PRODUCT_CODE" CHAR(6 BYTE), 
	"PRODUCT_BRAND" CHAR(15 BYTE), 
	"PRODUCT_PRICE" NUMBER(8,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table PRODUCT_LIKE
--------------------------------------------------------

  CREATE TABLE "HKL"."PRODUCT_LIKE" 
   (	"PRODUCT_LIKE_MEMBER_ID" CHAR(15 BYTE), 
	"PRODUCT_LIKE_PRODUCT_CODE" CHAR(6 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT_ORDER
--------------------------------------------------------

  CREATE TABLE "HKL"."PRODUCT_ORDER" 
   (	"ORDER_NUMBER" NUMBER, 
	"ORDER_MEMBER_ID" CHAR(15 BYTE), 
	"ORDER_PRODUCT_CODE" CHAR(6 BYTE), 
	"ORDER_DATE" DATE, 
	"ORDER_STATE" VARCHAR2(20 BYTE) DEFAULT '상품 준비 중'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table PRODUCT_STOCK
--------------------------------------------------------

  CREATE TABLE "HKL"."PRODUCT_STOCK" 
   (	"STOCK_PRODUCT_CODE" CHAR(6 BYTE), 
	"STOCK_240" VARCHAR2(20 BYTE), 
	"STOCK_250" VARCHAR2(20 BYTE), 
	"STOCK_260" VARCHAR2(20 BYTE), 
	"STOCK_270" VARCHAR2(20 BYTE), 
	"STOCK_280" VARCHAR2(20 BYTE), 
	"STOCK_290" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOARD_ASK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HKL"."BOARD_ASK_PK" ON "HKL"."BOARD_ASK" ("BOARD_ASK_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOARD_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HKL"."BOARD_COMMENT_PK" ON "HKL"."BOARD_COMMENT" ("BOARD_COMMENT_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOARD_REVIEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HKL"."BOARD_REVIEW_PK" ON "HKL"."BOARD_REVIEW" ("BOARD_REVIEW_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK_MEMBER_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HKL"."MEMBER_PK_MEMBER_ID" ON "HKL"."MEMBER" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HKL"."PRODUCT_PK" ON "HKL"."PRODUCT" ("PRODUCT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUCT_ORDER_PK_ORDER_NUMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "HKL"."PRODUCT_ORDER_PK_ORDER_NUMBER" ON "HKL"."PRODUCT_ORDER" ("ORDER_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  PARALLEL ;
--------------------------------------------------------
--  Constraints for Table BASKET
--------------------------------------------------------

  ALTER TABLE "HKL"."BASKET" MODIFY ("BASKET_MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BASKET" MODIFY ("BASKET_PRODUCT_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD_ASK
--------------------------------------------------------

  ALTER TABLE "HKL"."BOARD_ASK" MODIFY ("BOARD_ASK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BOARD_ASK" MODIFY ("BOARD_ASK_MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BOARD_ASK" MODIFY ("BOARD_ASK_DATE" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BOARD_ASK" MODIFY ("BOARD_ASK_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BOARD_ASK" MODIFY ("BOARD_ASK_TITLE" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BOARD_ASK" MODIFY ("BOARD_ASK_STATE" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BOARD_ASK" MODIFY ("BOARD_ASK_KIND" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BOARD_ASK" ADD CONSTRAINT "BOARD_ASK_PK" PRIMARY KEY ("BOARD_ASK_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "HKL"."BOARD_COMMENT" MODIFY ("BOARD_COMMENT_BOARD_REVIEW_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BOARD_COMMENT" MODIFY ("BOARD_COMMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BOARD_COMMENT" MODIFY ("BOARD_COMMENT_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BOARD_COMMENT" MODIFY ("BOARD_COMMENT_MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BOARD_COMMENT" ADD CONSTRAINT "BOARD_COMMENT_PK" PRIMARY KEY ("BOARD_COMMENT_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOARD_REVIEW
--------------------------------------------------------

  ALTER TABLE "HKL"."BOARD_REVIEW" MODIFY ("BOARD_REVIEW_MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BOARD_REVIEW" MODIFY ("BOARD_REVIEW_PRODUCT_CODE" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BOARD_REVIEW" MODIFY ("BOARD_REVIEW_TITLE" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BOARD_REVIEW" MODIFY ("BOARD_REVIEW_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BOARD_REVIEW" MODIFY ("BOARD_REVIEW_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HKL"."BOARD_REVIEW" ADD CONSTRAINT "BOARD_REVIEW_PK" PRIMARY KEY ("BOARD_REVIEW_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "HKL"."MEMBER" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "HKL"."MEMBER" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
  ALTER TABLE "HKL"."MEMBER" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "HKL"."MEMBER" MODIFY ("MEMBER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HKL"."MEMBER" MODIFY ("MEMBER_TEL" NOT NULL ENABLE);
  ALTER TABLE "HKL"."MEMBER" MODIFY ("MEMBER_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "HKL"."MEMBER" ADD CONSTRAINT "MEMBER_PK_MEMBER_ID" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HKL"."MEMBER" ADD CONSTRAINT "MEMBER_CK_MEMBER_EMAIL" CHECK (member_email like '%@%.%') ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "HKL"."PRODUCT" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "HKL"."PRODUCT" MODIFY ("PRODUCT_CODE" NOT NULL ENABLE);
  ALTER TABLE "HKL"."PRODUCT" MODIFY ("PRODUCT_BRAND" NOT NULL ENABLE);
  ALTER TABLE "HKL"."PRODUCT" MODIFY ("PRODUCT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "HKL"."PRODUCT" ADD CONSTRAINT "PRODUCT_PK_PRODUCT_CODE" PRIMARY KEY ("PRODUCT_CODE")
  USING INDEX (CREATE UNIQUE INDEX "HKL"."PRODUCT_PK" ON "HKL"."PRODUCT" ("PRODUCT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT_LIKE
--------------------------------------------------------

  ALTER TABLE "HKL"."PRODUCT_LIKE" MODIFY ("PRODUCT_LIKE_MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "HKL"."PRODUCT_LIKE" MODIFY ("PRODUCT_LIKE_PRODUCT_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT_ORDER
--------------------------------------------------------

  ALTER TABLE "HKL"."PRODUCT_ORDER" MODIFY ("ORDER_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HKL"."PRODUCT_ORDER" MODIFY ("ORDER_MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "HKL"."PRODUCT_ORDER" ADD CONSTRAINT "PRODUCT_ORDER_PK_ORDER_NUMBER" PRIMARY KEY ("ORDER_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HKL"."PRODUCT_ORDER" MODIFY ("ORDER_DATE" NOT NULL ENABLE);
  ALTER TABLE "HKL"."PRODUCT_ORDER" MODIFY ("ORDER_PRODUCT_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT_STOCK
--------------------------------------------------------

  ALTER TABLE "HKL"."PRODUCT_STOCK" MODIFY ("STOCK_PRODUCT_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BASKET
--------------------------------------------------------

  ALTER TABLE "HKL"."BASKET" ADD CONSTRAINT "BASKET_FK_MEMBER_ID" FOREIGN KEY ("BASKET_MEMBER_ID")
	  REFERENCES "HKL"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "HKL"."BASKET" ADD CONSTRAINT "BASKET_FK_PRODUCT_CODE" FOREIGN KEY ("BASKET_PRODUCT_CODE")
	  REFERENCES "HKL"."PRODUCT" ("PRODUCT_CODE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_ASK
--------------------------------------------------------

  ALTER TABLE "HKL"."BOARD_ASK" ADD CONSTRAINT "BOARD_ASK_FK_MEMBER_ID" FOREIGN KEY ("BOARD_ASK_MEMBER_ID")
	  REFERENCES "HKL"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "HKL"."BOARD_COMMENT" ADD CONSTRAINT "BOARD_COMMENT_FK_BOARD_REVIEW_NUMBER" FOREIGN KEY ("BOARD_COMMENT_BOARD_REVIEW_NUMBER")
	  REFERENCES "HKL"."BOARD_REVIEW" ("BOARD_REVIEW_NUMBER") ENABLE;
  ALTER TABLE "HKL"."BOARD_COMMENT" ADD CONSTRAINT "BOARD_COMMENT_FK_MEMBER_ID" FOREIGN KEY ("BOARD_COMMENT_MEMBER_ID")
	  REFERENCES "HKL"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_REVIEW
--------------------------------------------------------

  ALTER TABLE "HKL"."BOARD_REVIEW" ADD CONSTRAINT "BOARD_REVIEW_FK_PRODUCT_CODE" FOREIGN KEY ("BOARD_REVIEW_PRODUCT_CODE")
	  REFERENCES "HKL"."PRODUCT" ("PRODUCT_CODE") ENABLE;
  ALTER TABLE "HKL"."BOARD_REVIEW" ADD CONSTRAINT "BOARD_REVIEW_FK_MEMBER_ID" FOREIGN KEY ("BOARD_REVIEW_MEMBER_ID")
	  REFERENCES "HKL"."MEMBER" ("MEMBER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT_LIKE
--------------------------------------------------------

  ALTER TABLE "HKL"."PRODUCT_LIKE" ADD CONSTRAINT "PRODUCT_LIKE_FK_PRODUCT_CODE" FOREIGN KEY ("PRODUCT_LIKE_PRODUCT_CODE")
	  REFERENCES "HKL"."PRODUCT" ("PRODUCT_CODE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "HKL"."PRODUCT_LIKE" ADD CONSTRAINT "PRODUCT_LIKE_FK_MEMBER_ID" FOREIGN KEY ("PRODUCT_LIKE_MEMBER_ID")
	  REFERENCES "HKL"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT_ORDER
--------------------------------------------------------

  ALTER TABLE "HKL"."PRODUCT_ORDER" ADD CONSTRAINT "PRODUCT_ORDER_FK_PRODUCT_CODE" FOREIGN KEY ("ORDER_PRODUCT_CODE")
	  REFERENCES "HKL"."PRODUCT" ("PRODUCT_CODE") ENABLE;
  ALTER TABLE "HKL"."PRODUCT_ORDER" ADD CONSTRAINT "PRODUCT_ORDER_FK_MEMBER_ID" FOREIGN KEY ("ORDER_MEMBER_ID")
	  REFERENCES "HKL"."MEMBER" ("MEMBER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT_STOCK
--------------------------------------------------------

  ALTER TABLE "HKL"."PRODUCT_STOCK" ADD CONSTRAINT "PRODUCT_STOCK_FK_STOCK_PRODUCT_CODE" FOREIGN KEY ("STOCK_PRODUCT_CODE")
	  REFERENCES "HKL"."PRODUCT" ("PRODUCT_CODE") ENABLE;
